name: ready_lms
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  page_transition: ^2.0.9
  pretty_dio_logger: ^1.3.1
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0
  flutter_svg: ^2.0.10+1
  app_settings: ^5.1.1
  flutter_riverpod: ^2.1.3
  hive_flutter: ^1.1.0
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.1
  pinput: ^5.0.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  connectivity_wrapper: ^1.1.4
  flutter_localizations:
    sdk: flutter
  video_player: ^2.8.2
  device_preview: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  chewie: ^1.7.5
  webview_flutter: ^4.2.1
  flutter_pdfview: ^1.3.2
  flutter_html: ^3.0.0-beta.2
  flutter_native_image: ^0.0.6
  flutter_windowmanager: ^0.2.0
  device_info_plus: ^10.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: null
  flutter_gen_runner: null

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/ic_logo.png
  android: true
  # ios: true
flutter_icons:
  image_path_android: 'assets/images/ic_logo.png'
  image_path_ios: 'assets/images/ic_logo.png'
  android: true
#   ios: true
#   # change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/font/Lexend-Light.ttf
          weight: 300
        - asset: assets/font/Lexend-Regular.ttf
          weight: 400
        - asset: assets/font/Lexend-Medium.ttf
          weight: 500
        - asset: assets/font/Lexend-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
